version: 2
updates:
  # NuGet dependencies (.NET packages)
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
    open-pull-requests-limit: 10
    reviewers:
      - "mackowski"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "chore(nuget)"
      include: "scope"
    pull-request-branch-name:
      separator: "-"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
    open-pull-requests-limit: 5
    reviewers:
      - "mackowski"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(github-actions)"
      include: "scope"

  # Docker dependencies (for docker-compose.yml)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 14
    open-pull-requests-limit: 5
    reviewers:
      - "mackowski"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"
      include: "scope"
